name: test
on:
  workflow_dispatch:
    inputs:
      library-version:
        required: true
        default: ${{ secrets.TEST_PYPI_API_TOKEN }}
      pypi-repository-url:
        required: false
        default: ${{ secrets.TEST_PYPI_API_TOKEN }}
jobs:
  python-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        echo ${{ github.event.inputs.library-version }}
        echo ${{ github.event.inputs.pypi-repository-url }}
